// GENERATED FILE — do not edit. Source: proto/rpc-catalog.json (deno task generate in proto/).
// Declarative hub-passthrough specs for the daemon JSON-RPC dispatch.

/// One RPC param: canonical name, accepted aliases, requiredness, wire type.
pub struct ParamSpec {
    pub name: &'static str,
    pub aliases: &'static [&'static str],
    pub required: bool,
    /// Catalog type: string, bool, json, json[], string[].
    pub ty: &'static str,
}

/// One hub-passthrough RPC: verb + templated path + param routing + result shaping.
pub struct PassthroughSpec {
    pub name: &'static str,
    pub verb: &'static str,
    pub path: &'static str,
    pub path_params: &'static [ParamSpec],
    pub body_params: &'static [ParamSpec],
    /// (query_key, bool param) — appended as ?key=1 when the param is truthy.
    pub query_flags: &'static [(&'static str, ParamSpec)],
    /// Field plucked from the hub response before shaping the RPC result.
    pub hub_unwrap: Option<&'static str>,
    /// RPC result is wrapped as {wrap: value} when set.
    pub result_wrap: Option<&'static str>,
    /// RPC result is a bare {"ok": true} regardless of hub body.
    pub result_ok: bool,
}

pub const PASSTHROUGH_SPECS: &[PassthroughSpec] = &[
    PassthroughSpec {
        name: "list_external_contacts",
        verb: "GET",
        path: "/v1/contacts/external",
        path_params: &[],
        body_params: &[],
        query_flags: &[],
        hub_unwrap: Some("contacts"),
        result_wrap: Some("contacts"),
        result_ok: false,
    },
    PassthroughSpec {
        name: "get_registry_listing",
        verb: "GET",
        path: "/v1/registry/listing/{id_or_address}",
        path_params: &[ParamSpec { name: "id_or_address", aliases: &["address"], required: true, ty: "string" }],
        body_params: &[],
        query_flags: &[],
        hub_unwrap: None,
        result_wrap: None,
        result_ok: false,
    },
    PassthroughSpec {
        name: "issue_pairing_pin",
        verb: "POST",
        path: "/v1/contacts/pairing/pin",
        path_params: &[],
        body_params: &[],
        query_flags: &[],
        hub_unwrap: None,
        result_wrap: None,
        result_ok: false,
    },
    PassthroughSpec {
        name: "get_pairing_pin",
        verb: "GET",
        path: "/v1/contacts/pairing/pin",
        path_params: &[],
        body_params: &[],
        query_flags: &[],
        hub_unwrap: Some("pin"),
        result_wrap: Some("pin"),
        result_ok: false,
    },
    PassthroughSpec {
        name: "rotate_pairing_pin",
        verb: "POST",
        path: "/v1/contacts/pairing/pin/rotate",
        path_params: &[],
        body_params: &[],
        query_flags: &[],
        hub_unwrap: None,
        result_wrap: None,
        result_ok: false,
    },
    PassthroughSpec {
        name: "submit_pair_request",
        verb: "POST",
        path: "/v1/contacts/pairing/request",
        path_params: &[],
        body_params: &[ParamSpec { name: "handle", aliases: &[], required: true, ty: "string" }, ParamSpec { name: "pin", aliases: &[], required: true, ty: "string" }, ParamSpec { name: "intro", aliases: &[], required: false, ty: "string" }],
        query_flags: &[],
        hub_unwrap: Some("request"),
        result_wrap: Some("request"),
        result_ok: false,
    },
    PassthroughSpec {
        name: "list_pending_pair_requests",
        verb: "GET",
        path: "/v1/contacts/pairing/pending",
        path_params: &[],
        body_params: &[],
        query_flags: &[],
        hub_unwrap: None,
        result_wrap: None,
        result_ok: false,
    },
    PassthroughSpec {
        name: "approve_pair_request",
        verb: "POST",
        path: "/v1/contacts/pairing/{request_id}/approve",
        path_params: &[ParamSpec { name: "request_id", aliases: &[], required: true, ty: "string" }],
        body_params: &[],
        query_flags: &[],
        hub_unwrap: None,
        result_wrap: None,
        result_ok: false,
    },
    PassthroughSpec {
        name: "deny_pair_request",
        verb: "POST",
        path: "/v1/contacts/pairing/{request_id}/deny",
        path_params: &[ParamSpec { name: "request_id", aliases: &[], required: true, ty: "string" }],
        body_params: &[],
        query_flags: &[],
        hub_unwrap: None,
        result_wrap: None,
        result_ok: true,
    },
    PassthroughSpec {
        name: "unpair_external_contact",
        verb: "DELETE",
        path: "/v1/contacts/external/{link_id}",
        path_params: &[ParamSpec { name: "link_id", aliases: &[], required: true, ty: "string" }],
        body_params: &[],
        query_flags: &[],
        hub_unwrap: None,
        result_wrap: None,
        result_ok: false,
    },
    PassthroughSpec {
        name: "propose_thread_downgrade",
        verb: "POST",
        path: "/v1/threads/{thread_id}/downgrade-proposals",
        path_params: &[ParamSpec { name: "thread_id", aliases: &[], required: true, ty: "string" }],
        body_params: &[ParamSpec { name: "agent_slug", aliases: &[], required: true, ty: "string" }, ParamSpec { name: "from_agent", aliases: &[], required: false, ty: "string" }],
        query_flags: &[],
        hub_unwrap: None,
        result_wrap: None,
        result_ok: false,
    },
    PassthroughSpec {
        name: "list_pending_thread_downgrades",
        verb: "GET",
        path: "/v1/threads/downgrade-proposals/pending",
        path_params: &[],
        body_params: &[],
        query_flags: &[],
        hub_unwrap: None,
        result_wrap: None,
        result_ok: false,
    },
    PassthroughSpec {
        name: "deny_thread_downgrade",
        verb: "POST",
        path: "/v1/threads/{thread_id}/downgrade-proposals/{proposal_id}/deny",
        path_params: &[ParamSpec { name: "thread_id", aliases: &[], required: true, ty: "string" }, ParamSpec { name: "proposal_id", aliases: &[], required: true, ty: "string" }],
        body_params: &[],
        query_flags: &[],
        hub_unwrap: Some("proposal"),
        result_wrap: Some("proposal"),
        result_ok: false,
    },
    PassthroughSpec {
        name: "list_collabs",
        verb: "GET",
        path: "/v1/collabs",
        path_params: &[],
        body_params: &[],
        query_flags: &[("archived", ParamSpec { name: "include_archived", aliases: &["archived"], required: false, ty: "bool" })],
        hub_unwrap: None,
        result_wrap: None,
        result_ok: false,
    },
    PassthroughSpec {
        name: "add_collab_steerer",
        verb: "POST",
        path: "/v1/collabs/{collab_id}/steerers",
        path_params: &[ParamSpec { name: "collab_id", aliases: &[], required: true, ty: "string" }],
        body_params: &[ParamSpec { name: "handle", aliases: &[], required: true, ty: "string" }],
        query_flags: &[],
        hub_unwrap: Some("collab"),
        result_wrap: Some("collab"),
        result_ok: false,
    },
    PassthroughSpec {
        name: "remove_collab_steerer",
        verb: "POST",
        path: "/v1/collabs/{collab_id}/steerers/remove",
        path_params: &[ParamSpec { name: "collab_id", aliases: &[], required: true, ty: "string" }],
        body_params: &[ParamSpec { name: "user_id", aliases: &[], required: true, ty: "string" }],
        query_flags: &[],
        hub_unwrap: Some("collab"),
        result_wrap: Some("collab"),
        result_ok: false,
    },
    PassthroughSpec {
        name: "add_collab_roster",
        verb: "POST",
        path: "/v1/collabs/{collab_id}/roster",
        path_params: &[ParamSpec { name: "collab_id", aliases: &[], required: true, ty: "string" }],
        body_params: &[ParamSpec { name: "address", aliases: &[], required: true, ty: "string" }],
        query_flags: &[],
        hub_unwrap: Some("collab"),
        result_wrap: Some("collab"),
        result_ok: false,
    },
    PassthroughSpec {
        name: "remove_collab_roster",
        verb: "POST",
        path: "/v1/collabs/{collab_id}/roster/remove",
        path_params: &[ParamSpec { name: "collab_id", aliases: &[], required: true, ty: "string" }],
        body_params: &[ParamSpec { name: "agent_id", aliases: &[], required: true, ty: "string" }],
        query_flags: &[],
        hub_unwrap: Some("collab"),
        result_wrap: Some("collab"),
        result_ok: false,
    },
    PassthroughSpec {
        name: "archive_collab",
        verb: "POST",
        path: "/v1/collabs/{collab_id}/archive",
        path_params: &[ParamSpec { name: "collab_id", aliases: &[], required: true, ty: "string" }],
        body_params: &[],
        query_flags: &[],
        hub_unwrap: Some("collab"),
        result_wrap: Some("collab"),
        result_ok: false,
    },
    PassthroughSpec {
        name: "unarchive_collab",
        verb: "POST",
        path: "/v1/collabs/{collab_id}/unarchive",
        path_params: &[ParamSpec { name: "collab_id", aliases: &[], required: true, ty: "string" }],
        body_params: &[],
        query_flags: &[],
        hub_unwrap: Some("collab"),
        result_wrap: Some("collab"),
        result_ok: false,
    },
    PassthroughSpec {
        name: "approve_collab_pending_membership",
        verb: "POST",
        path: "/v1/collabs/{collab_id}/downgrade/approve",
        path_params: &[ParamSpec { name: "collab_id", aliases: &[], required: true, ty: "string" }],
        body_params: &[],
        query_flags: &[],
        hub_unwrap: Some("collab"),
        result_wrap: Some("collab"),
        result_ok: false,
    },
    PassthroughSpec {
        name: "deny_collab_pending_membership",
        verb: "POST",
        path: "/v1/collabs/{collab_id}/downgrade/deny",
        path_params: &[ParamSpec { name: "collab_id", aliases: &[], required: true, ty: "string" }],
        body_params: &[],
        query_flags: &[],
        hub_unwrap: Some("collab"),
        result_wrap: Some("collab"),
        result_ok: false,
    },
    PassthroughSpec {
        name: "set_default_agent",
        verb: "PUT",
        path: "/v1/agents/default",
        path_params: &[],
        body_params: &[ParamSpec { name: "agent_id", aliases: &[], required: true, ty: "string" }],
        query_flags: &[],
        hub_unwrap: Some("agent"),
        result_wrap: None,
        result_ok: false,
    },
    PassthroughSpec {
        name: "rename_agent",
        verb: "PATCH",
        path: "/v1/agents/{agent_id}",
        path_params: &[ParamSpec { name: "agent_id", aliases: &[], required: true, ty: "string" }],
        body_params: &[ParamSpec { name: "slug", aliases: &[], required: true, ty: "string" }],
        query_flags: &[],
        hub_unwrap: Some("agent"),
        result_wrap: None,
        result_ok: false,
    },
    PassthroughSpec {
        name: "get_router",
        verb: "GET",
        path: "/v1/agents/router",
        path_params: &[],
        body_params: &[],
        query_flags: &[],
        hub_unwrap: None,
        result_wrap: None,
        result_ok: false,
    },
    PassthroughSpec {
        name: "set_router",
        verb: "PUT",
        path: "/v1/agents/router",
        path_params: &[],
        body_params: &[ParamSpec { name: "default_agent_id", aliases: &[], required: false, ty: "string" }, ParamSpec { name: "rules", aliases: &[], required: false, ty: "json[]" }],
        query_flags: &[],
        hub_unwrap: None,
        result_wrap: None,
        result_ok: false,
    },
    PassthroughSpec {
        name: "get_transport_defaults",
        verb: "GET",
        path: "/v1/agents/transport-defaults",
        path_params: &[],
        body_params: &[],
        query_flags: &[],
        hub_unwrap: None,
        result_wrap: None,
        result_ok: false,
    },
];
